import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Apresentacao from '../section/apresentacao'
import Portfolio from '../section/portfolio'
import Skill from '../section/skill'
import Sobre from '../section/sobre'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Apresentacao />
        <Skill />
        <Sobre />
        <Portfolio />
       </main>
    </div>
  )
}
